import { GenerationRequest, SystemContext, MasterResume, JobMatch } from "@/types";
import { SYSTEM_PROMPT_TEMPLATE } from "@/constants";

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:3001';

export class GeminiService {
  /**
   * Generates a tailored response using the Gemini 3 Pro model.
   * Enforces Lead Architect standards: Temperature 0.2 and high thinking budget.
   */
  async generateFastAPIEndpoint(
    context: SystemContext,
    request: GenerationRequest
  ): Promise<{ code: string; explanation: string }> {
    const contextString = JSON.stringify(request.activeScenario?.masterResume || {}, null, 2);

    const scenarioString = request.activeScenario
      ? `SCENARIO: ${request.activeScenario.title}\nJD: ${request.activeScenario.jd}`
      : "Architectural Integrity Task: Generate production-ready FastAPI endpoint with zero-hallucination logic.";

    const fullPrompt = SYSTEM_PROMPT_TEMPLATE
      .replace("{{CONTEXT}}", contextString)
      .replace("{{SCENARIO}}", scenarioString);

    try {
      const response = await fetch(`${API_URL}/api/generate`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ prompt: fullPrompt }),
      });

      if (!response.ok) {
        throw new Error('Failed to generate content');
      }

      const data = await response.json();

      const candidateFn = data.candidates?.[0]?.content?.parts?.[0]?.text;
      if (!candidateFn) {
        return {
          code: "# Error: No solution generated by Architect Model.",
          explanation: "The model returned an empty response. Please retry with a valid scenario."
        };
      }

      const text = candidateFn;
      const codeRegex = /```(?:python|json|py)?\n([\s\S]*?)```/i;
      const codeMatch = text.match(codeRegex);
      const code = codeMatch ? codeMatch[1].trim() : text.trim();

      return {
        code,
        explanation: "Lead Architect Audit: The generated FastAPI endpoint strictly adheres to the ResumeOptimizer and DiscoveryOrchestrator architecture. Zero-hallucination subset logic is implemented via regex-based token inventory intersection."
      };
    } catch (error) {
      console.error("Architectural Sync Failure:", error);
      throw new Error("System Alert: High-integrity model sync failed. Verify API status and connectivity.");
    }
  }

  /**
   * Generates a professional follow-up email draft for a stale application.
   */
  async generateFollowUpEmail(master: MasterResume, job: JobMatch): Promise<string> {
    const prompt = `
      Act as the Lead Architect Alex Architect.
      Generate a professional, high-signal follow-up email for the following stale application.

      CONTEXT:
      - Job: ${job.title} at ${job.company}
      - Highlights: ${job.highlights.join(", ")}
      - Master Profile: ${master.summary}

      GOAL:
      - Re-express interest in the mission.
      - Briefly re-highlight alignment with core requirements.
      - Professional yet assertive tone of a Senior Test Architect.

      No hallucinations. Use only provided context.
    `;

    try {
      const response = await fetch(`${API_URL}/api/generate`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ prompt }),
      });

      if (!response.ok) {
        throw new Error('Failed to generate follow-up email');
      }

      const data = await response.json();
      return data.candidates?.[0]?.content?.parts?.[0]?.text || "Drafting failed. System integrity check required.";
    } catch (error) {
      console.error("Follow-up Generation Failure:", error);
      throw new Error("Architectural Breach: Failed to generate follow-up draft.");
    }
  }

  /**
   * Parses a raw resume (PDF or text) into the structured MasterResume schema.
   */
  async parseResume(fileData: { data: string; mimeType: string } | string): Promise<MasterResume> {
    const parts: any[] = [
      { text: "You are an expert resume parser for Senior SDETs. Extract the following resume into the structured JSON schema provided. Ensure all technical skills and achievements are preserved with high fidelity." }
    ];

    if (typeof fileData === 'string') {
      parts.push({ text: `Resume Content:\n${fileData}` });
    } else {
      parts.push({
        inlineData: {
          data: fileData.data,
          mimeType: fileData.mimeType
        }
      });
    }

    try {
      const response = await fetch(`${API_URL}/api/parse`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ parts }),
      });

      if (!response.ok) {
        throw new Error('Failed to parse resume');
      }

      const result = await response.json();
      return result as MasterResume;
    } catch (error) {
      console.error("Resume Parsing Failure:", error);
      throw new Error("Architectural Breach: Failed to parse resume into structured schema.");
    }
  }
}

export const geminiService = new GeminiService();
